@startuml
scale 500 width

[*] --> 草稿 : 页面新建、修改通知（包含内容检测）
'[*] --> 待发送 : 生成消息，未到达推送时间
'[*] --> 已发送未读 : 页面发送、系统发送

草稿 --> 待发送 : 短信二次验证（延迟发送、未达到发送时间）
草稿 -left-> 已发送未读 : 短信二次验证（立即发送）
待发送 --> 已发送未读 : 延时消息到达推送时间发送
待发送 --> 已取消 : 撤回
已发送未读 --> 已读 : 用户查看消息
已发送未读 --> 已取消 : 撤回（安卓端）


已读 --> [*]
已取消 --> [*]
@enduml
