permission:
  config:
    msgcenter:
      umeng:
        androidAppKey:
        androidAppMasterSecret:
        iosAppKey:
        iosAppMasterSecret:
    netty:
      port: 9090
    decrypt:
      decrypt-secret-key: permission
spring:
  redis:
    ################### redis 单机版 start ##########################
    host: p(jlntwUv5DX3uDiFbj+JiQiuLRrjrMqzW)
    port: 3306
    password: p(YM3AQrYJQBNT7lcbIVsi8hQwXsYhr4I9)
    timeout: 6000
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 10
        # 连接池中的最大空闲连接 ，默认值也是8
        max-idle: 8
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 100
        # 连接池中的最小空闲连接 ，默认值也是0
        min-idle: 2
      shutdown-timeout: 100ms
  # sharding-jdbc 数据源配置
  shardingsphere:
    datasource:
      names: permissions0, leaf0, workflow0
      permissions0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: p(HXx+bGz9zEIn+cYJA/gikDptY9uPpu6nPBqmiFWil8CLEov0H1VZOcf0Oj8Y/Xy3kJVgKPj2rWB69LWGUSea0wVjH38sXE9XPhk4vakMeJpZt8zOzJAKEMa2ycuxwiwTiQgGlFngqUki034mvGJjPRYvqmvua+BMFg5ATQPajRdAz2nowmOM447zWu5W8PGXR7CFCup18qR2kpj7ccVD8b6Io4B5auTkrlMZQUUfX7h5n+wwoaWJnHH4eYy0o7PRQWcrO6cq0r7IpIrmd+PwjfAZvm5j8OKX)
        username: p(cGjOBN6vq5pdJKq7vWsw5g==)
        password: p(gYrMfK4xVuhzzoveGLRJwlaxEZTtnH3Zb9bzkYa1Ty4=)
      leaf0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: p(uCPLsGCT/Lq92qzJYzT0hHW9wQWW5YQWlKKVeiH0xBM3BbHwb4u4Z7tBey5JrtlT8obgckPWkWktcF/EevcW2IM7qmQB3q1HgvU3jBvmArlRMk4zp7bxHSV987g5ff1oE511yP3V+uIN1pXSErhDwguYs8XWu1bijjNCwmKJbYKJ7yfbca+Ca8/lZEFHOYMF53ThX7TZTt1g7/h0+KujcdlcjfJSPkSVLmS8biYpaVkykYbSv7A/Ig1yJdskqDioXvtNbNfl7rA=)
        username: p(cGjOBN6vq5pdJKq7vWsw5g==)
        password: p(gYrMfK4xVuhzzoveGLRJwlaxEZTtnH3Zb9bzkYa1Ty4=)
      workflow0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: p(Mrw7iDE0JgtcoitMhfCanu0UyyEBcLOq7cHWWYyS3LZO8lnO87NSQ4I2GhpSBpO91xTE64TGCKev8LaYIAeUNHhX+KyomVJI7W8K9NvkhfZl5UDxj90FQF3AHombj2MujGbS6B2Drj6mb9cDx0VcmolafgPn3nBnU1wwnu8ZHLxK2pAWbnezE5yYI3a3KsKo5Yvq+Ff2B2/VyrDaBHL/6l8+b/xrPX9UxGxSUQX+E/VOP+YxDVNa2k5CCT/5wx4EqzQBTi6FHp344472NX5Hvg==)
        username: p(cGjOBN6vq5pdJKq7vWsw5g==)
        password: p(gYrMfK4xVuhzzoveGLRJwlaxEZTtnH3Zb9bzkYa1Ty4=)
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: permissions0
      default-database-strategy:
        none:
          any:
      default-table-strategy:
        none:
          any:
      tables:
        leaf:
          actual-data-nodes: leaf0.leaf_alloc
        thread_pool_data:
          actual-data-nodes: permissions0.thread_pool_data_$->{2021..2022}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
          table-strategy:
            standard:
              sharding-column: sharding_key
              precise-algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.sharding.ThreadPoolDataShardingAlgorithm
        workflow:
          actual-data-nodes: workflow0.ACT_*, workflow0.FLW_*, workflow0.workflow_*
flowable:
  # 如果是手动创建的flowable表，此参数必须要设置为false, 否则启动报错
  database-schema-update: false
  # 关闭异步任务
  async-executor-activate: false

security:
  api:
    permit-all:
      - /login/usernamePasswordLogin
      - /login/validateCodeLogin
      - /validateCode/sendCode
      - /validateCode/sendSmsCode
      - /validateCode/sendEmailCode

mq:
  redis:
    topic:
      quartzJobChange:
        name: quartz-job-change-channel
      operateChatRoom:
        name: operate-chat-room
      chatRoomNodeListener:
        name: chat-room-node
      chatRoomNodeListenerPattern:
        name: chat-room-node:*
      groupChatListenerNode:
        name: group-chat-Node
      groupChatListenerNodePattern:
        name: group-chat-Node:*

system:
  upload:
    path: /upload
  local:
    file:
      uri: http://localhost:8080/showImage/
