permission:
  config:
    msgcenter:
      umeng:
        androidAppKey:
        androidAppMasterSecret:
        iosAppKey:
        iosAppMasterSecret:
    netty:
      port: 9090
spring:
  redis:
    ################### redis 单机版 start ##########################
    host: 121.37.67.125
    port: 6379
    password: fyk961222..
    timeout: 6000
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 10
        # 连接池中的最大空闲连接 ，默认值也是8
        max-idle: 8
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 100
        # 连接池中的最小空闲连接 ，默认值也是0
        min-idle: 2
      shutdown-timeout: 100ms
  # sharding-jdbc 数据源配置
  shardingsphere:
    datasource:
      names: permissions0, leaf0, edi0, workflow0
      permissions0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.234.219.109:3306/permissions-center?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: root
      leaf0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.234.219.109:3306/leaf?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: root
      edi0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.234.219.109:3306/edi?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: root
      workflow0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.234.219.109:3306/workflow?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: root
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: permissions0
      default-database-strategy:
        none:
          any:
      default-table-strategy:
        none:
          any:
      tables:
        # EDI
        edi_cfg_biz_retry:
          actual-data-nodes: edi0.edi_cfg_biz_retry
        edi_biz_retry_record:
          actual-data-nodes: edi0.edi_biz_retry_record_$->{2022..2023}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}_$->{0..3}
          table-strategy:
            standard:
              sharding-column: sharding_key
              precise-algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.edi.core.BizRetryShardingAlgorithm
        retry_biz_record_task:
          actual-data-nodes: edi0.edi_biz_retry_record_$->{2022..2023}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}_$->{0..3}
          database-strategy:
            hint:
              algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.edi.core.BizRetryTaskShardingHintAlgorithm
          table-strategy:
            hint:
              algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.edi.core.BizRetryTaskShardingHintAlgorithm
        # TECH-EDI
        edi_cfg_tech_biz_retry:
          actual-data-nodes: edi0.edi_cfg_tech_biz_retry
        edi_tech_biz_retry_record:
          actual-data-nodes: edi0.edi_tech_biz_retry_record_$->{2022..2023}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}_$->{0..3}
          key-generator:
            type: SNOWFLAKE
            column: id
            props:
              worker.id: 0
              max.tolerate.time.difference.milliseconds: 0
              max.vibration.offset: 1000
          table-strategy:
            standard:
              sharding-column: sharding_key
              precise-algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.edi.core.TechBizRetryShardingAlgorithm
        retry_tech_biz_record_task:
          actual-data-nodes: edi0.edi_tech_biz_retry_record_$->{2022..2023}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}_$->{0..3}
          database-strategy:
            hint:
              algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.edi.core.BizRetryTaskShardingHintAlgorithm
          table-strategy:
            hint:
              algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.edi.core.BizRetryTaskShardingHintAlgorithm
        leaf:
          actual-data-nodes: leaf0.leaf_alloc
        thread_pool_data:
          actual-data-nodes: permissions0.thread_pool_data_$->{2021..2022}$->{['01','02','03','04','05','06','07','08','09','10','11','12']}
          table-strategy:
            standard:
              sharding-column: sharding_key
              precise-algorithm-class-name: com.ah.cloud.permissions.biz.infrastructure.sharding.ThreadPoolDataShardingAlgorithm
        workflow:
          actual-data-nodes: workflow0.ACT_*, workflow0.FLW_*
flowable:
  # 如果是手动创建的flowable表，此参数必须要设置为false, 否则启动报错
  database-schema-update: false
  # 关闭异步任务
  async-executor-activate: false

security:
  api:
    permit-all:
      - /login/usernamePasswordLogin
      - /login/validateCodeLogin
      - /validateCode/sendCode
      - /validateCode/sendSmsCode
      - /validateCode/sendEmailCode

mq:
  redis:
    topic:
      quartzJobChange:
        name: quartz-job-change-channel
      operateChatRoom:
        name: operate-chat-room
      chatRoomNodeListener:
        name: chat-room-node
      chatRoomNodeListenerPattern:
        name: chat-room-node:*
      groupChatListenerNode:
        name: group-chat-Node
      groupChatListenerNodePattern:
        name: group-chat-Node:*

system:
  upload:
    path: /upload
  local:
    file:
      uri: http://localhost:8080/showImage/
