server:
  port: 8080

# 建议放一些通用的、与环境无关、与系统相关的配置在这里
# SpringBoot的相关配置
spring:
  profiles:
    active: prod
  application:
    name: permissions-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# slf4j日志配置
logging:
  config: classpath:logback-spring.xml
  path: ./logs/ypsx-logistics-platform/
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure: ERROR

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
